name: flutter_template
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  # sdk: ^3.7.2
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 
  go_router: ^16.2.1
  freezed_annotation: ^2.4.4
  shimmer: ^3.0.0
  http: ^1.5.0
  dartz: ^0.10.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  build_runner: ^2.4.15
  freezed: ^2.5.8



flutter:

 
  uses-material-design: true

  assets:
    - assets/
  
